#!/usr/bin/env python
import sys
import os
import unittest
from mock import patch, MagicMock, ANY, call

import pylacuna.core.map

import ast

from sys import version_info
if version_info.major == 2:
    import __builtin__ as builtins  # pylint:disable=import-error
else:
    import builtins  # pylint:disable=import-error

GET_STAR_MAP_RESPONSE = ast.literaleval('''
{u'id': 7,
 u'jsonrpc': u'2.0',
 u'result': {u'stars': [{u'bodies': [{u'id': u'356648',
      u'image': u'p18-1',
      u'name': u'Kleahien 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 4200,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 3200,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2600,
       u'zircon': 1},
      u'size': u'50',
      u'star_id': u'49528',
      u'star_name': u'Kleahien',
      u'type': u'habitable planet',
      u'water': 7600,
      u'x': u'416',
      u'y': u'-261',
      u'zone': u'1|-1'},
     {u'id': u'356649',
      u'image': u'p28-2',
      u'name': u'Kleahien 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'68',
      u'star_id': u'49528',
      u'star_name': u'Kleahien',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'417',
      u'y': u'-262',
      u'zone': u'1|-1'},
     {u'empire': {u'alignment': u'hostile',
       u'id': u'38995',
       u'is_isolationist': u'0',
       u'name': u'dev'},
      u'id': u'356650',
      u'image': u'p38-3',
      u'name': u'Polyhedra 3',
      u'orbit': u'3',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49528',
      u'star_name': u'Kleahien',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'417',
      u'y': u'-264',
      u'zone': u'1|-1'},
     {u'id': u'356651',
      u'image': u'a22-5',
      u'name': u'Kleahien 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 900,
       u'beryl': 1,
       u'chalcopyrite': 700,
       u'chromite': 900,
       u'fluorite': 100,
       u'galena': 800,
       u'goethite': 400,
       u'gold': 100,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 500,
       u'methane': 1,
       u'monazite': 300,
       u'rutile': 800,
       u'sulfur': 1,
       u'trona': 400,
       u'uraninite': 1,
       u'zircon': 200},
      u'size': u'6',
      u'star_id': u'49528',
      u'star_name': u'Kleahien',
      u'type': u'asteroid',
      u'x': u'414',
      u'y': u'-265',
      u'zone': u'1|-1'},
     {u'id': u'356652',
      u'image': u'p37-6',
      u'name': u'Kleahien 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'60',
      u'star_id': u'49528',
      u'star_name': u'Kleahien',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'413',
      u'y': u'-264',
      u'zone': u'1|-1'},
     {u'id': u'356653',
      u'image': u'p7-8',
      u'name': u'Kleahien 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1700,
       u'beryl': 1000,
       u'chalcopyrite': 2800,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2400,
       u'gold': 1,
       u'gypsum': 2100,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'57',
      u'star_id': u'49528',
      u'star_name': u'Kleahien',
      u'type': u'habitable planet',
      u'water': 5700,
      u'x': u'414',
      u'y': u'-261',
      u'zone': u'1|-1'}],
    u'color': u'magenta',
    u'id': u'49528',
    u'influence': u'0',
    u'name': u'Kleahien',
    u'x': u'415',
    u'y': u'-263',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'359536',
      u'image': u'pg4-1',
      u'name': u'Chea Oobixy 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 2000,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 14000,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 4000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'105',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'418',
      u'y': u'-251',
      u'zone': u'1|-1'},
     {u'id': u'359537',
      u'image': u'p7-2',
      u'name': u'Chea Oobixy 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1700,
       u'beryl': 1000,
       u'chalcopyrite': 2800,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2400,
       u'gold': 1,
       u'gypsum': 2100,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'66',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'habitable planet',
      u'water': 5700,
      u'x': u'419',
      u'y': u'-252',
      u'zone': u'1|-1'},
     {u'id': u'359538',
      u'image': u'p10-3',
      u'name': u'Tau chy 1',
      u'orbit': u'3',
      u'ore': {u'anthracite': 500,
       u'bauxite': 1,
       u'beryl': 250,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 250,
       u'galena': 1,
       u'goethite': 1000,
       u'gold': 1,
       u'gypsum': 500,
       u'halite': 1,
       u'kerogen': 500,
       u'magnetite': 5000,
       u'methane': 500,
       u'monazite': 250,
       u'rutile': 1,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 1,
       u'zircon': 250},
      u'size': u'45',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'habitable planet',
      u'water': 6800,
      u'x': u'419',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'id': u'359539',
      u'image': u'p18-4',
      u'name': u'Toppie Terra',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 4200,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 3200,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2600,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'habitable planet',
      u'water': 7600,
      u'x': u'418',
      u'y': u'-255',
      u'zone': u'1|-1'},
     {u'id': u'359540',
      u'image': u'pg4-5',
      u'name': u'Chea Oobixy 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 2000,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 14000,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 4000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'95',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'416',
      u'y': u'-255',
      u'zone': u'1|-1'},
     {u'id': u'359541',
      u'image': u'p38-6',
      u'name': u'Chea Oobixy 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'55',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'415',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'id': u'359542',
      u'image': u'p5-7',
      u'name': u'Chea Oobixy 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 2250,
       u'beryl': 1,
       u'chalcopyrite': 250,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 2250,
       u'goethite': 1250,
       u'gold': 1,
       u'gypsum': 1250,
       u'halite': 250,
       u'kerogen': 1,
       u'magnetite': 250,
       u'methane': 250,
       u'monazite': 1,
       u'rutile': 1250,
       u'sulfur': 250,
       u'trona': 250,
       u'uraninite': 250,
       u'zircon': 1},
      u'size': u'52',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'habitable planet',
      u'water': 6200,
      u'x': u'415',
      u'y': u'-252',
      u'zone': u'1|-1'},
     {u'id': u'359543',
      u'image': u'p37-8',
      u'name': u'Chea Oobixy 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'49',
      u'star_id': u'49928',
      u'star_name': u'Chea Oobixy',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'416',
      u'y': u'-251',
      u'zone': u'1|-1'}],
    u'color': u'blue',
    u'id': u'49928',
    u'influence': u'0',
    u'name': u'Chea Oobixy',
    u'x': u'417',
    u'y': u'-253',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'362428',
      u'image': u'a13-1',
      u'name': u'Tchia Thowdo Oxy 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 6574,
       u'uraninite': 1,
       u'zircon': 2590},
      u'size': u'10',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'418',
      u'y': u'-241',
      u'zone': u'1|0'},
     {u'id': u'362429',
      u'image': u'a12-2',
      u'name': u'Tchia Thowdo Oxy 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 289,
       u'bauxite': 269,
       u'beryl': 313,
       u'chalcopyrite': 299,
       u'chromite': 320,
       u'fluorite': 307,
       u'galena': 278,
       u'goethite': 292,
       u'gold': 310,
       u'gypsum': 311,
       u'halite': 301,
       u'kerogen': 284,
       u'magnetite': 296,
       u'methane': 285,
       u'monazite': 319,
       u'rutile': 258,
       u'sulfur': 324,
       u'trona': 293,
       u'uraninite': 276,
       u'zircon': 275},
      u'size': u'6',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'419',
      u'y': u'-242',
      u'zone': u'1|0'},
     {u'id': u'362430',
      u'image': u'a3-3',
      u'name': u'Tchia Thowdo Oxy 3',
      u'orbit': u'3',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1000,
       u'zircon': 8000},
      u'size': u'9',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'419',
      u'y': u'-244',
      u'zone': u'1|0'},
     {u'id': u'362431',
      u'image': u'a20-4',
      u'name': u'Tchia Thowdo Oxy 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 6342,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'2',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'418',
      u'y': u'-245',
      u'zone': u'1|0'},
     {u'id': u'362432',
      u'image': u'a20-5',
      u'name': u'Tchia Thowdo Oxy 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 6342,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'6',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'416',
      u'y': u'-245',
      u'zone': u'1|0'},
     {u'id': u'362433',
      u'image': u'a14-6',
      u'name': u'Tchia Thowdo Oxy 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 3038,
       u'goethite': 2895,
       u'gold': 1,
       u'gypsum': 2897,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'9',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'415',
      u'y': u'-244',
      u'zone': u'1|0'},
     {u'id': u'362434',
      u'image': u'a12-7',
      u'name': u'Tchia Thowdo Oxy 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 289,
       u'bauxite': 269,
       u'beryl': 313,
       u'chalcopyrite': 299,
       u'chromite': 320,
       u'fluorite': 307,
       u'galena': 278,
       u'goethite': 292,
       u'gold': 310,
       u'gypsum': 311,
       u'halite': 301,
       u'kerogen': 284,
       u'magnetite': 296,
       u'methane': 285,
       u'monazite': 319,
       u'rutile': 258,
       u'sulfur': 324,
       u'trona': 293,
       u'uraninite': 276,
       u'zircon': 275},
      u'size': u'4',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'415',
      u'y': u'-242',
      u'zone': u'1|0'},
     {u'id': u'362435',
      u'image': u'a2-8',
      u'name': u'Tchia Thowdo Oxy 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 4000,
       u'chalcopyrite': 5000,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1000},
      u'size': u'2',
      u'star_id': u'50328',
      u'star_name': u'Tchia Thowdo Oxy',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'416',
      u'y': u'-241',
      u'zone': u'1|0'}],
    u'color': u'white',
    u'id': u'50328',
    u'influence': u'227',
    u'name': u'Tchia Thowdo Oxy',
    u'station': {u'id': u'360983',
     u'name': u'SASS 5',
     u'x': u'424',
     u'y': u'-213'},
    u'x': u'417',
    u'y': u'-243',
    u'zone': u'1|0'},
   {u'bodies': [{u'id': u'360995',
      u'image': u'a20-1',
      u'name': u'Oum Froassoo Sta 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 6342,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'5',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'424',
      u'y': u'-243',
      u'zone': u'1|0'},
     {u'id': u'360996',
      u'image': u'a14-2',
      u'name': u'Oum Froassoo Sta 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 3038,
       u'goethite': 2895,
       u'gold': 1,
       u'gypsum': 2897,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'8',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'425',
      u'y': u'-244',
      u'zone': u'1|0'},
     {u'id': u'360997',
      u'image': u'a3-3',
      u'name': u'Oum Froassoo Sta 3',
      u'orbit': u'3',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1000,
       u'zircon': 8000},
      u'size': u'3',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'425',
      u'y': u'-246',
      u'zone': u'1|0'},
     {u'id': u'360998',
      u'image': u'pg3-4',
      u'name': u'Oum Froassoo Sta 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 4000,
       u'halite': 14000,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 2000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'88',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'424',
      u'y': u'-247',
      u'zone': u'1|0'},
     {u'id': u'360999',
      u'image': u'pg4-5',
      u'name': u'Oum Froassoo Sta 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 2000,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 14000,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 4000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'107',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'422',
      u'y': u'-247',
      u'zone': u'1|0'},
     {u'id': u'361000',
      u'image': u'a18-6',
      u'name': u'Oum Froassoo Sta 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 4120,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 3326,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'7',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'421',
      u'y': u'-246',
      u'zone': u'1|0'},
     {u'id': u'361001',
      u'image': u'a13-7',
      u'name': u'Oum Froassoo Sta 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 6574,
       u'uraninite': 1,
       u'zircon': 2590},
      u'size': u'6',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'421',
      u'y': u'-244',
      u'zone': u'1|0'},
     {u'id': u'361002',
      u'image': u'a4-8',
      u'name': u'Oum Froassoo Sta 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1000,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 9000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'3',
      u'star_id': u'50129',
      u'star_name': u'Oum Froassoo Sta',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'422',
      u'y': u'-243',
      u'zone': u'1|0'}],
    u'color': u'white',
    u'id': u'50129',
    u'influence': u'254',
    u'name': u'Oum Froassoo Sta',
    u'station': {u'id': u'360983',
     u'name': u'SASS 5',
     u'x': u'424',
     u'y': u'-213'},
    u'x': u'423',
    u'y': u'-245',
    u'zone': u'1|0'},
   {u'bodies': [{u'id': u'358097',
      u'image': u'pg3-1',
      u'name': u'Ouss Siek 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 4000,
       u'halite': 14000,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 2000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'104',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'425',
      u'y': u'-253',
      u'zone': u'1|-1'},
     {u'id': u'358098',
      u'image': u'p28-2',
      u'name': u'Ouss Siek 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'64',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'426',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'build_queue_len': 7,
      u'build_queue_size': 9,
      u'building_count': 43,
      u'empire': {u'alignment': u'self',
       u'id': u'51819',
       u'is_isolationist': u'1',
       u'name': u'MikeTwo'},
      u'energy_capacity': u'280094',
      u'energy_hour': u'3537',
      u'energy_stored': u'104737',
      u'food_capacity': u'284472',
      u'food_hour': 5171,
      u'food_stored': 284472,
      u'happiness': u'352459',
      u'happiness_hour': u'680',
      u'id': u'358099',
      u'image': u'p38-3',
      u'incoming_enemy_ships': [{u'date_arrives': u'06 09 2015 18:33:00 +0000',
        u'id': u'51549238',
        u'is_ally': 0,
        u'is_own': 0}],
      u'name': u'Cloraphorm III',
      u'needs_surface_refresh': u'0',
      u'neutral_entry': u'10 07 2015 07:26:44 +0000',
      u'num_incoming_ally': u'0',
      u'num_incoming_enemy': u'1',
      u'num_incoming_own': u'0',
      u'orbit': u'3',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'ore_capacity': u'295866',
      u'ore_hour': 7794,
      u'ore_stored': 202664,
      u'plots_available': u'2',
      u'population': 2880000,
      u'propaganda_boost': u'0',
      u'size': u'45',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'surface_version': u'358',
      u'type': u'habitable planet',
      u'waste_capacity': u'289133',
      u'waste_hour': u'239',
      u'waste_stored': u'288328',
      u'water': 8000,
      u'water_capacity': u'280094',
      u'water_hour': u'5476',
      u'water_stored': u'280094',
      u'x': u'426',
      u'y': u'-256',
      u'zone': u'1|-1'},
     {u'id': u'358100',
      u'image': u'a7-4',
      u'name': u'Ouss Siek 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3291,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1239,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2377,
       u'zircon': 1},
      u'size': u'5',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'asteroid',
      u'x': u'425',
      u'y': u'-257',
      u'zone': u'1|-1'},
     {u'id': u'358101',
      u'image': u'p28-5',
      u'name': u'Ouss Siek 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'56',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'423',
      u'y': u'-257',
      u'zone': u'1|-1'},
     {u'id': u'358102',
      u'image': u'p37-6',
      u'name': u'Ouss Siek 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'53',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'422',
      u'y': u'-256',
      u'zone': u'1|-1'},
     {u'id': u'358103',
      u'image': u'pg3-7',
      u'name': u'Ouss Siek 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 4000,
       u'halite': 14000,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 2000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'86',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'422',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'id': u'358104',
      u'image': u'p37-8',
      u'name': u'Ouss Siek 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'69',
      u'star_id': u'49729',
      u'star_name': u'Ouss Siek',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'423',
      u'y': u'-253',
      u'zone': u'1|-1'}],
    u'color': u'blue',
    u'id': u'49729',
    u'influence': u'0',
    u'name': u'Ouss Siek',
    u'x': u'424',
    u'y': u'-255',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'355186',
      u'image': u'a12-1',
      u'name': u'Iondeuzz 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 289,
       u'bauxite': 269,
       u'beryl': 313,
       u'chalcopyrite': 299,
       u'chromite': 320,
       u'fluorite': 307,
       u'galena': 278,
       u'goethite': 292,
       u'gold': 310,
       u'gypsum': 311,
       u'halite': 301,
       u'kerogen': 284,
       u'magnetite': 296,
       u'methane': 285,
       u'monazite': 319,
       u'rutile': 258,
       u'sulfur': 324,
       u'trona': 293,
       u'uraninite': 276,
       u'zircon': 275},
      u'size': u'8',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'asteroid',
      u'x': u'426',
      u'y': u'-265',
      u'zone': u'1|-1'},
     {u'id': u'355187',
      u'image': u'p13-2',
      u'name': u'Iondeuzz 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1500,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1300,
       u'chromite': 1400,
       u'fluorite': 1,
       u'galena': 2200,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1500,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 2100,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'66',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'habitable planet',
      u'water': 8300,
      u'x': u'427',
      u'y': u'-266',
      u'zone': u'1|-1'},
     {u'id': u'355188',
      u'image': u'p10-3',
      u'name': u'Iondeuzz 3',
      u'orbit': u'3',
      u'ore': {u'anthracite': 500,
       u'bauxite': 1,
       u'beryl': 250,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 250,
       u'galena': 1,
       u'goethite': 1000,
       u'gold': 1,
       u'gypsum': 500,
       u'halite': 1,
       u'kerogen': 500,
       u'magnetite': 5000,
       u'methane': 500,
       u'monazite': 250,
       u'rutile': 1,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 1,
       u'zircon': 250},
      u'size': u'45',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'habitable planet',
      u'water': 6800,
      u'x': u'427',
      u'y': u'-268',
      u'zone': u'1|-1'},
     {u'id': u'355189',
      u'image': u'p18-4',
      u'name': u"Khim'bar",
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 4200,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 3200,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2600,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'habitable planet',
      u'water': 7600,
      u'x': u'426',
      u'y': u'-269',
      u'zone': u'1|-1'},
     {u'id': u'355190',
      u'image': u'p28-5',
      u'name': u'Iondeuzz 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'58',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'424',
      u'y': u'-269',
      u'zone': u'1|-1'},
     {u'id': u'355191',
      u'image': u'p38-6',
      u'name': u'Iondeuzz 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'55',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'423',
      u'y': u'-268',
      u'zone': u'1|-1'},
     {u'id': u'355192',
      u'image': u'p5-8',
      u'name': u'Iondeuzz 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 2250,
       u'beryl': 1,
       u'chalcopyrite': 250,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 2250,
       u'goethite': 1250,
       u'gold': 1,
       u'gypsum': 1250,
       u'halite': 250,
       u'kerogen': 1,
       u'magnetite': 250,
       u'methane': 250,
       u'monazite': 1,
       u'rutile': 1250,
       u'sulfur': 250,
       u'trona': 250,
       u'uraninite': 250,
       u'zircon': 1},
      u'size': u'53',
      u'star_id': u'49329',
      u'star_name': u'Iondeuzz',
      u'type': u'habitable planet',
      u'water': 6200,
      u'x': u'424',
      u'y': u'-265',
      u'zone': u'1|-1'}],
    u'color': u'yellow',
    u'id': u'49329',
    u'influence': u'0',
    u'name': u'Iondeuzz',
    u'x': u'425',
    u'y': u'-267',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'301055',
      u'image': u'p36-4',
      u'name': u'Aegh Oxyeufr 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 100,
       u'beryl': 1,
       u'chalcopyrite': 100,
       u'chromite': 100,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 100,
       u'gold': 1,
       u'gypsum': 100,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 100,
       u'rutile': 100,
       u'sulfur': 100,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 30000,
      u'x': u'431',
      u'y': u'-263',
      u'zone': u'1|-1'},
     {u'empire': {u'alignment': u'hostile',
       u'id': u'50180',
       u'is_isolationist': u'0',
       u'name': u'Cybertronian Defense League'},
      u'id': u'332066',
      u'image': u'p35-3',
      u'name': u'in4',
      u'orbit': u'3',
      u'ore': {u'anthracite': 500,
       u'bauxite': 500,
       u'beryl': 500,
       u'chalcopyrite': 500,
       u'chromite': 500,
       u'fluorite': 500,
       u'galena': 500,
       u'goethite': 500,
       u'gold': 500,
       u'gypsum': 500,
       u'halite': 500,
       u'kerogen': 500,
       u'magnetite': 500,
       u'methane': 500,
       u'monazite': 500,
       u'rutile': 500,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 500,
       u'zircon': 500},
      u'size': u'70',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 9467,
      u'x': u'432',
      u'y': u'-262',
      u'zone': u'1|-1'},
     {u'id': u'356654',
      u'image': u'p10-1',
      u'name': u'Ovoahuij 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 500,
       u'bauxite': 1,
       u'beryl': 250,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 250,
       u'galena': 1,
       u'goethite': 1000,
       u'gold': 1,
       u'gypsum': 500,
       u'halite': 1,
       u'kerogen': 500,
       u'magnetite': 5000,
       u'methane': 500,
       u'monazite': 250,
       u'rutile': 1,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 1,
       u'zircon': 250},
      u'size': u'55',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 6800,
      u'x': u'431',
      u'y': u'-259',
      u'zone': u'1|-1'},
     {u'id': u'356655',
      u'image': u'p18-2',
      u'name': u'Ovoahuij 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 4200,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 3200,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2600,
       u'zircon': 1},
      u'size': u'52',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 7600,
      u'x': u'432',
      u'y': u'-260',
      u'zone': u'1|-1'},
     {u'id': u'356658',
      u'image': u'p18-5',
      u'name': u'Ovoahuij 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 4200,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 3200,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2600,
       u'zircon': 1},
      u'size': u'65',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 7600,
      u'x': u'429',
      u'y': u'-263',
      u'zone': u'1|-1'},
     {u'id': u'356659',
      u'image': u'p28-6',
      u'name': u'Alajuwon',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'428',
      u'y': u'-262',
      u'zone': u'1|-1'},
     {u'id': u'356660',
      u'image': u'p38-7',
      u'name': u'Ovoahuij 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'59',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'428',
      u'y': u'-260',
      u'zone': u'1|-1'},
     {u'id': u'356661',
      u'image': u'p5-8',
      u'name': u'Ovoahuij 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 2250,
       u'beryl': 1,
       u'chalcopyrite': 250,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 2250,
       u'goethite': 1250,
       u'gold': 1,
       u'gypsum': 1250,
       u'halite': 250,
       u'kerogen': 1,
       u'magnetite': 250,
       u'methane': 250,
       u'monazite': 1,
       u'rutile': 1250,
       u'sulfur': 250,
       u'trona': 250,
       u'uraninite': 250,
       u'zircon': 1},
      u'size': u'56',
      u'star_id': u'49529',
      u'star_name': u'Ovoahuij',
      u'type': u'habitable planet',
      u'water': 6200,
      u'x': u'429',
      u'y': u'-259',
      u'zone': u'1|-1'}],
    u'color': u'blue',
    u'id': u'49529',
    u'influence': u'0',
    u'name': u'Ovoahuij',
    u'x': u'430',
    u'y': u'-261',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'353720',
      u'image': u'a7-1',
      u'name': u'Plia Osloy Sai 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3291,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1239,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2377,
       u'zircon': 1},
      u'size': u'4',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'asteroid',
      u'x': u'433',
      u'y': u'-268',
      u'zone': u'1|-1'},
     {u'id': u'353721',
      u'image': u'p28-2',
      u'name': u'severus',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'434',
      u'y': u'-269',
      u'zone': u'1|-1'},
     {u'id': u'353722',
      u'image': u'p38-4',
      u'name': u'Plia Osloy Sai 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'51',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'433',
      u'y': u'-272',
      u'zone': u'1|-1'},
     {u'id': u'353723',
      u'image': u'p5-5',
      u'name': u'Plia Osloy Sai 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 2250,
       u'beryl': 1,
       u'chalcopyrite': 250,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 2250,
       u'goethite': 1250,
       u'gold': 1,
       u'gypsum': 1250,
       u'halite': 250,
       u'kerogen': 1,
       u'magnetite': 250,
       u'methane': 250,
       u'monazite': 1,
       u'rutile': 1250,
       u'sulfur': 250,
       u'trona': 250,
       u'uraninite': 250,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'habitable planet',
      u'water': 6200,
      u'x': u'431',
      u'y': u'-272',
      u'zone': u'1|-1'},
     {u'id': u'353724',
      u'image': u'p37-6',
      u'name': u'T8TE Alpha',
      u'orbit': u'6',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'430',
      u'y': u'-271',
      u'zone': u'1|-1'},
     {u'id': u'353725',
      u'image': u'p37-7',
      u'name': u'Plia Osloy Sai 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'64',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'430',
      u'y': u'-269',
      u'zone': u'1|-1'},
     {u'id': u'353726',
      u'image': u'p5-8',
      u'name': u'Plia Osloy Sai 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 2250,
       u'beryl': 1,
       u'chalcopyrite': 250,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 2250,
       u'goethite': 1250,
       u'gold': 1,
       u'gypsum': 1250,
       u'halite': 250,
       u'kerogen': 1,
       u'magnetite': 250,
       u'methane': 250,
       u'monazite': 1,
       u'rutile': 1250,
       u'sulfur': 250,
       u'trona': 250,
       u'uraninite': 250,
       u'zircon': 1},
      u'size': u'61',
      u'star_id': u'49129',
      u'star_name': u'Plia Osloy Sai',
      u'type': u'habitable planet',
      u'water': 6200,
      u'x': u'431',
      u'y': u'-268',
      u'zone': u'1|-1'}],
    u'color': u'magenta',
    u'id': u'49129',
    u'influence': u'0',
    u'name': u'Plia Osloy Sai',
    u'x': u'432',
    u'y': u'-270',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'359544',
      u'image': u'p7-1',
      u'name': u'Iostr Ufeass 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1700,
       u'beryl': 1000,
       u'chalcopyrite': 2800,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2400,
       u'gold': 1,
       u'gypsum': 2100,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'habitable planet',
      u'water': 5700,
      u'x': u'433',
      u'y': u'-250',
      u'zone': u'1|-1'},
     {u'id': u'359545',
      u'image': u'p10-2',
      u'name': u'Coraton',
      u'orbit': u'2',
      u'ore': {u'anthracite': 500,
       u'bauxite': 1,
       u'beryl': 250,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 250,
       u'galena': 1,
       u'goethite': 1000,
       u'gold': 1,
       u'gypsum': 500,
       u'halite': 1,
       u'kerogen': 500,
       u'magnetite': 5000,
       u'methane': 500,
       u'monazite': 250,
       u'rutile': 1,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 1,
       u'zircon': 250},
      u'size': u'45',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'habitable planet',
      u'water': 6800,
      u'x': u'434',
      u'y': u'-251',
      u'zone': u'1|-1'},
     {u'id': u'359546',
      u'image': u'p37-3',
      u'name': u'Iostr Ufeass 3',
      u'orbit': u'3',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'434',
      u'y': u'-253',
      u'zone': u'1|-1'},
     {u'id': u'359547',
      u'image': u'a16-4',
      u'name': u'Iostr Ufeass 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1894,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1793,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 2132,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 2018,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'5',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'asteroid',
      u'x': u'433',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'id': u'359548',
      u'image': u'p10-5',
      u'name': u'Iostr Ufeass 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 500,
       u'bauxite': 1,
       u'beryl': 250,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 250,
       u'galena': 1,
       u'goethite': 1000,
       u'gold': 1,
       u'gypsum': 500,
       u'halite': 1,
       u'kerogen': 500,
       u'magnetite': 5000,
       u'methane': 500,
       u'monazite': 250,
       u'rutile': 1,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 1,
       u'zircon': 250},
      u'size': u'57',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'habitable planet',
      u'water': 6800,
      u'x': u'431',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'id': u'359549',
      u'image': u'pg3-6',
      u'name': u'Iostr Ufeass 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 4000,
       u'halite': 14000,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 2000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'90',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'gas giant',
      u'water': 0,
      u'x': u'430',
      u'y': u'-253',
      u'zone': u'1|-1'},
     {u'id': u'359550',
      u'image': u'p28-7',
      u'name': u'Iostr Ufeass 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'51',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'430',
      u'y': u'-251',
      u'zone': u'1|-1'},
     {u'id': u'359551',
      u'image': u'p38-8',
      u'name': u'Iostr Ufeass 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'49',
      u'star_id': u'49929',
      u'star_name': u'Iostr Ufeass',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'431',
      u'y': u'-250',
      u'zone': u'1|-1'}],
    u'color': u'white',
    u'id': u'49929',
    u'influence': u'0',
    u'name': u'Iostr Ufeass',
    u'x': u'432',
    u'y': u'-252',
    u'zone': u'1|-1'},
   {u'bodies': [{u'id': u'362436',
      u'image': u'a1-1',
      u'name': u'Vlea Isphern Oaly 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1000,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 9000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'7',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'433',
      u'y': u'-241',
      u'zone': u'1|0'},
     {u'id': u'362437',
      u'image': u'a20-2',
      u'name': u'Vlea Isphern Oaly 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 6342,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'1',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'434',
      u'y': u'-242',
      u'zone': u'1|0'},
     {u'id': u'362438',
      u'image': u'a1-3',
      u'name': u'Vlea Isphern Oaly 3',
      u'orbit': u'3',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1000,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 9000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'4',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'434',
      u'y': u'-244',
      u'zone': u'1|0'},
     {u'id': u'362439',
      u'image': u'a23-4',
      u'name': u'Vlea Isphern Oaly 4',
      u'orbit': u'4',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1000,
       u'chalcopyrite': 1000,
       u'chromite': 1000,
       u'fluorite': 1000,
       u'galena': 1000,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1000,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1000},
      u'size': u'8',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'433',
      u'y': u'-245',
      u'zone': u'1|0'},
     {u'id': u'362440',
      u'image': u'a13-5',
      u'name': u'Vlea Isphern Oaly 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 6574,
       u'uraninite': 1,
       u'zircon': 2590},
      u'size': u'7',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'431',
      u'y': u'-245',
      u'zone': u'1|0'},
     {u'id': u'362441',
      u'image': u'a2-6',
      u'name': u'Vlea Isphern Oaly 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 4000,
       u'chalcopyrite': 5000,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1000},
      u'size': u'3',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'430',
      u'y': u'-244',
      u'zone': u'1|0'},
     {u'id': u'362442',
      u'image': u'a9-7',
      u'name': u'Vlea Isphern Oaly 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 5500,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'6',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'430',
      u'y': u'-242',
      u'zone': u'1|0'},
     {u'id': u'362443',
      u'image': u'a10-8',
      u'name': u'Vlea Isphern Oaly 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 6250,
       u'bauxite': 108,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 55,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 300,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'9',
      u'star_id': u'50329',
      u'star_name': u'Vlea Isphern Oaly',
      u'station': {u'id': u'360983',
       u'name': u'SASS 5',
       u'x': u'424',
       u'y': u'-213'},
      u'type': u'asteroid',
      u'x': u'431',
      u'y': u'-241',
      u'zone': u'1|0'}],
    u'color': u'magenta',
    u'id': u'50329',
    u'influence': u'276',
    u'name': u'Vlea Isphern Oaly',
    u'station': {u'id': u'360983',
     u'name': u'SASS 5',
     u'x': u'424',
     u'y': u'-213'},
    u'x': u'432',
    u'y': u'-243',
    u'zone': u'1|0'},
   {u'color': u'blue',
    u'id': u'50130',
    u'influence': u'192',
    u'name': u'Aw Ohaeph Vli',
    u'x': u'438',
    u'y': u'-247',
    u'zone': u'1|0'},
   {u'bodies': [{u'id': u'358105',
      u'image': u'p13-1',
      u'name': u'Chou Idow 1',
      u'orbit': u'1',
      u'ore': {u'anthracite': 1500,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1300,
       u'chromite': 1400,
       u'fluorite': 1,
       u'galena': 2200,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1500,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 2100,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'45',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 8300,
      u'x': u'440',
      u'y': u'-254',
      u'zone': u'1|-1'},
     {u'id': u'358106',
      u'image': u'p10-2',
      u'name': u'Chou Idow 2',
      u'orbit': u'2',
      u'ore': {u'anthracite': 500,
       u'bauxite': 1,
       u'beryl': 250,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 250,
       u'galena': 1,
       u'goethite': 1000,
       u'gold': 1,
       u'gypsum': 500,
       u'halite': 1,
       u'kerogen': 500,
       u'magnetite': 5000,
       u'methane': 500,
       u'monazite': 250,
       u'rutile': 1,
       u'sulfur': 500,
       u'trona': 500,
       u'uraninite': 1,
       u'zircon': 250},
      u'size': u'63',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 6800,
      u'x': u'441',
      u'y': u'-255',
      u'zone': u'1|-1'},
     {u'empire': {u'alignment': u'hostile',
       u'id': u'46258',
       u'is_isolationist': u'0',
       u'name': u'Last Legion'},
      u'id': u'358107',
      u'image': u'p18-3',
      u'name': u'in1',
      u'orbit': u'3',
      u'ore': {u'anthracite': 1,
       u'bauxite': 4200,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 3200,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2600,
       u'zircon': 1},
      u'size': u'70',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 7600,
      u'x': u'441',
      u'y': u'-257',
      u'zone': u'1|-1'},
     {u'id': u'358108',
      u'image': u'p28-5',
      u'name': u'Chou Idow 5',
      u'orbit': u'5',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1500,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 2500,
       u'gold': 1,
       u'gypsum': 2000,
       u'halite': 3500,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 1500,
       u'zircon': 1},
      u'size': u'58',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 9230,
      u'x': u'438',
      u'y': u'-258',
      u'zone': u'1|-1'},
     {u'id': u'358109',
      u'image': u'p38-6',
      u'name': u'Chou Idow 6',
      u'orbit': u'6',
      u'ore': {u'anthracite': 1,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 3000,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 1,
       u'magnetite': 1,
       u'methane': 1,
       u'monazite': 1,
       u'rutile': 1,
       u'sulfur': 7000,
       u'trona': 1,
       u'uraninite': 1,
       u'zircon': 1},
      u'size': u'55',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 8000,
      u'x': u'437',
      u'y': u'-257',
      u'zone': u'1|-1'},
     {u'id': u'358110',
      u'image': u'p5-7',
      u'name': u'Chou Idow 7',
      u'orbit': u'7',
      u'ore': {u'anthracite': 1,
       u'bauxite': 2250,
       u'beryl': 1,
       u'chalcopyrite': 250,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 2250,
       u'goethite': 1250,
       u'gold': 1,
       u'gypsum': 1250,
       u'halite': 250,
       u'kerogen': 1,
       u'magnetite': 250,
       u'methane': 250,
       u'monazite': 1,
       u'rutile': 1250,
       u'sulfur': 250,
       u'trona': 250,
       u'uraninite': 250,
       u'zircon': 1},
      u'size': u'52',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 6200,
      u'x': u'437',
      u'y': u'-255',
      u'zone': u'1|-1'},
     {u'id': u'358111',
      u'image': u'p37-8',
      u'name': u'Chou Idow 8',
      u'orbit': u'8',
      u'ore': {u'anthracite': 2000,
       u'bauxite': 1,
       u'beryl': 1,
       u'chalcopyrite': 1,
       u'chromite': 1,
       u'fluorite': 1,
       u'galena': 1,
       u'goethite': 1,
       u'gold': 1,
       u'gypsum': 1,
       u'halite': 1,
       u'kerogen': 2000,
       u'magnetite': 2000,
       u'methane': 1,
       u'monazite': 2000,
       u'rutile': 1,
       u'sulfur': 1,
       u'trona': 1,
       u'uraninite': 2000,
       u'zircon': 1},
      u'size': u'50',
      u'star_id': u'49730',
      u'star_name': u'Chou Idow',
      u'type': u'habitable planet',
      u'water': 6225,
      u'x': u'438',
      u'y': u'-254',
      u'zone': u'1|-1'}],
    u'color': u'green',
    u'id': u'49730',
    u'influence': u'0',
    u'name': u'Chou Idow',
    u'x': u'439',
    u'y': u'-256',
    u'zone': u'1|-1'},
   {u'color': u'magenta',
    u'id': u'49330',
    u'influence': u'0',
    u'name': u'Eckladdee',
    u'x': u'440',
    u'y': u'-267',
    u'zone': u'1|-1'}],
  u'status': {u'empire': {u'alliance_id': u'1785',
    u'colonies': {u'358099': u'Cloraphorm III'},
    u'essentia': 0,
    u'has_new_messages': u'0',
    u'home_planet_id': u'358099',
    u'id': u'51819',
    u'insurrect_value': u'100000',
    u'is_isolationist': u'1',
    u'latest_message_id': u'0',
    u'name': u'MikeTwo',
    u'next_colony_cost': u'100000',
    u'next_colony_srcs': u'100000',
    u'next_station_cost': u'108696',
    u'planets': {u'358099': u'Cloraphorm III'},
    u'primary_embassy_id': u'5048765',
    u'rpc_count': 276,
    u'self_destruct_active': u'0',
    u'self_destruct_date': u'08 06 2015 05:49:38 +0000',
    u'stations': {},
    u'status_message': u'Just getting started',
    u'tech_level': u'9'},
   u'server': {u'rpc_limit': 10000,
    u'star_map_size': {u'x': [-1500, 1500], u'y': [-1500, 1500]},
    u'time': u'10 07 2015 17:41:04 +0000',
    u'version': 3.0911}}}}
''')

def mock_api(route, method, params=None):
    if method == 'view':
        print "MOCK: Returning individual view"
        return MagicMock()
    if method == 'get_buildings':
        print "MOCK: Returning get buildings response"
        return MagicMock()
    print "MOCK: Returning mock"
    return MagicMock()


class testMap(unittest.TestCase):
    def setUp(self):
        # Create session mock
        self.session_mock = MagicMock()
        self.session_mock.call_method_with_session_id.side_effect = mock_api

        # Patch out stdout
        # use 'reload(sys)' in a test to undo
        # patcher = patch('sys.stdout')
        # patcher.start()
        # self.addCleanup(patcher.stop)

    def tearDown(self):
        pass

    def test_init_and_print(self):
        mymap = pylacuna.core.map.Map(self.session_mock)
        print mymap
        print self.mock_body.mock_calls
        print self.session_mock.mock_calls

if __name__ == '__main__':
    unittest.main()
